sudo: required
services:
  - docker

before_install:
  - docker build -t kadekchrisna/react-test -f Dockerfile.dev ./client

script:
  - docker run -e CI=true kadekchrisna/react-test npm run test

after_success:
  - docker build -t kadekchrisna/multi-client ./client
  - docker build -t kadekchrisna/multi-nginx ./nginx
  - docker build -t kadekchrisna/multi-server ./server
  - docker build -t kadekchrisna/multi-worker ./worker
