sudo: required
services:
  - docker

before_install:
  - docker build -t kadekchresna/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kadekchresna/react-test npm run test

after_success:
  - docker build -t kadekchresna/multi-client ./client
  - docker build -t kadekchresna/multi-nginx ./nginx
  - docker build -t kadekchresna/multi-server ./server
  - docker build -t kadekchresna/multi-worker ./worker

  # Login to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push image to Docker Hub
  - docker push kadekchresna/multi-client
  - docker push kadekchresna/multi-nginx
  - docker push kadekchresna/multi-server
  - docker push kadekchresna/multi-worker

deploy:
  edge: true
  provider: "elasticbeanstalk"
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-469244896249"
  bucker_path: "multi-docker"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY
